### ISSUE TITLE
Enable Labs to have Lab specific Blog post which are not part of the /Blog feed

### ISSUE THREAD

**Issue by iamsilvio** [okfde/codefor.de#287]
- Differentiate between
  - Lab only
  - Lab and Global
  - Global only

- Add a RSS Feed for each Lab
- Add latest blog posts to the Lab Page

**Comment by sonjafischbauer** [comment]
in the course of the project to update the website (2023) we decided against this feature. reasons being that we currently do not have a lot of content for the blog anyways, and would want more content on the main feed instead of less. Labs can already feature their articles (meta tag: lab-name) on their sub pages.
